version: '3.4'

services:
  products_transpiler:
    build:
      context: ./products
    volumes:
      - ./products:/app
      - ./products/dist:/app/dist
    command: node_modules/typescript/bin/tsc -w --outDir /app/dist --skipLibCheck

  products_server:
    build:
      context: ./products
    volumes:
      - ./products:/app
      - ./products/dist:/app/dist
    command: node_modules/nodemon/bin/nodemon.js -w /app/dist/ /app/dist/index.js
    ports:
      - 3000:3000
    networks:
      - network
    depends_on:
      - products_transpiler
      - localstack

  products_test:
    build:
      context: ./products
    volumes:
      - ./products:/app
      - ./products/dist:/app/dist
    command: node_modules/.bin/ava tests/

  localstack:
    image: localstack/localstack
    ports:
      - 4564:4564 # shell dynamondb
    expose:
      - 4569 # dynamondb
    networks:
      - network

  database_seed:
    build:
      context: ./products
    volumes:
      - ./products:/app
      - ./products/dist:/app/dist
    command: node /app/dist/database/seeds.js
    networks:
      - network
    depends_on:
      - localstack

  discount_server:
    build:
      context: ./discount
    volumes:
      - ./discount:/app

networks:
  network:
