version: 2.1

jobs:
  products_test_unit:
    machine: true
    steps:
      - checkout
      - run: docker-compose run products_test_unit
  products_test_functional:
    machine: true
    steps:
      - checkout
      - run: docker-compose run products_test_functional
  products_test_e2e:
    machine: true
    steps:
      - checkout
      - run: docker-compose run products_test_e2e
  products_lint:
    machine: true
    steps:
      - checkout
      - run: docker-compose run products_lint
  discount_test:
    machine: true
    steps:
      - checkout
      - run: docker-compose run discount_test
  discount_lint:
    machine: true
    steps:
      - checkout
      - run: docker-compose run discount_lint

workflows:
  version: 2
  tests:
    jobs:
      - products_test_unit
      - products_test_functional
      - products_test_e2e
      - products_lint
      - discount_test
      - discount_lint
